### ISSUE TITLE
Chapter 12: 'Data_Wrangling_With_R_Chapter10.docx' seems to be missing from the repo

### ISSUE THREAD

**Issue by AnttiRask** [PacktPublishing/Data-Wrangling-with-R#1]
"As the text input for this exercise, I will use the chapter 10 of this book."

The .docx file is nowhere to be found.

I've been reading the book and going through the code while I'm at it. There have been some minor issues, but this is the first real roadblock.

**Comment by saurabhk710** [comment]
HI @gurezende ! can you please help @AnttiRask  with this ?

**Comment by gurezende** [comment]
Sure. That's closed. I have added the .docx file for the exercise. Thanks.

**Comment by gurezende** [comment]
Sure. That's closed. I have added the .docx file for the exercise. Thanks.
